import folium
from streamlit_folium import st_folium
import re 
import fitz 
import io
import markdown
from xhtml2pdf import pisa
import streamlit as st
import pandas as pd
import database as db
import agent
import streamlit.components.v1 as components
import json


# --- 1. PAGE CONFIG ---
st.set_page_config(page_title="Personal Healthcare Monitor", layout="wide", page_icon="🩺")

# --- THE INVISIBLE SHIELD (UNIVERSAL CLEANER) ---
# Ye function AI ke har message ko filter karega display hone se pehle
def clean_ai_response(text):
    if not text:
        return text
    # 1. Remove manual LOG tags
    cleaned = re.sub(r'\[LOG_.*?\]', '', text)
    # 2. Remove complete function blocks: <function=...>...</function>
    cleaned = re.sub(r'<function=.*?>.*?</function>', '', cleaned, flags=re.DOTALL)
    # 3. Remove unclosed opening tags: <function=...>
    cleaned = re.sub(r'<function=.*?>', '', cleaned)
    # 4. Catch-all for any cut-off function tags at the end of the string
    cleaned = re.sub(r'<function=.*', '', cleaned, flags=re.DOTALL)
    # 5. Remove simple </function> or <function>
    cleaned = re.sub(r'</?function>', '', cleaned)
    
    return cleaned.strip()

# --- INITIALIZE REAL-TIME DATABASE (Session State + SQLite Connection) ---
if "live_meds" not in st.session_state:
    # Fetching from SQLite Database
    saved_meds = db.get_all_medicines()
    st.session_state.live_meds = [{"med": m[1], "time": m[2]} for m in saved_meds] if saved_meds else []

if "live_fitness" not in st.session_state:
    # Fetching from SQLite Database
    saved_fitness = db.get_recent_fitness_logs()
    
    # Extract only numbers from the string
    clean_fitness = []
    if saved_fitness:
        for f in saved_fitness:
            only_numbers = re.sub(r'\D', '', str(f[1])) 
            clean_dur = int(only_numbers) if only_numbers else 0
            clean_fitness.append({"activity": f[0], "duration": clean_dur})
            
    st.session_state.live_fitness = clean_fitness

if "health_facts" not in st.session_state:
    with st.spinner("✨ Fetching today's Health Facts..."):
        st.session_state.health_facts = agent.get_dynamic_health_facts()
        if "water_intake" not in st.session_state:
            st.session_state.water_intake = 0
# --- 2. PDF GENERATOR FUNCTION ---
def create_professional_pdf(ai_markdown_text):
    html_content = markdown.markdown(ai_markdown_text, extensions=['tables'])
    pdf_html = f"""
    <html>
    <head>
        <style>
            @page {{ margin: 2cm; }}
            body {{ font-family: Helvetica, Arial, sans-serif; color: #111827; line-height: 1.6; font-size: 12px; }}
            h1 {{ color: #000000; border-bottom: 2px solid #000000; padding-bottom: 5px; }}
            h2, h3, h4 {{ color: #1E293B; margin-top: 15px; }}
            p {{ margin-bottom: 10px; }}
            ul {{ margin-bottom: 15px; }}
            li {{ margin-bottom: 5px; }}
            .footer {{ text-align: center; color: #6B7280; font-size: 10px; margin-top: 30px; border-top: 1px solid #E5E7EB; padding-top: 10px; }}
        </style>
    </head>
    <body>
        <h1>Personal Healthcare Monitor</h1>
        <h3>AI Medical Report Analysis</h3>
        <p><i>Generated by HopeRise Health AI</i></p>
        <br>
        {html_content}
        <div class="footer">
            Disclaimer: This is an AI-generated analysis. Please consult a certified doctor for medical decisions.
        </div>
    </body>
    </html>
    """
    pdf_buffer = io.BytesIO()
    pisa.CreatePDF(io.StringIO(pdf_html), dest=pdf_buffer)
    return pdf_buffer.getvalue()

# --- 3. GLOBAL UI/UX INJECTION ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap');
    .stApp{
        background:#F8FAFC !important;
        font-family:'Outfit',sans-serif !important;
    }
    /* Sidebar */
    [data-testid="stSidebar"]{
        background:linear-gradient(
            180deg,
            #F8FAFC,
            #ECFEFF
        ) !important;
        border-right:none !important;
    }

    /* Buttons */
    .stButton > button{
        background:linear-gradient(
            135deg,
            #0F766E,
            #14B8A6
        ) !important;
        color:white !important;
        border:none !important;
        border-radius:14px !important;
        font-weight:600 !important;
        padding:0.7rem 1.4rem !important;
        transition:0.3s !important;
    }
    .stButton > button:hover{
        transform:translateY(-2px);
    }
    /* Tabs */
    .stTabs [data-baseweb="tab"]{
        background:white !important;
        border:1px solid #E2E8F0 !important;
        border-radius:12px !important;
        color:#475569 !important;
        font-weight:600 !important;
    }

    .stTabs [aria-selected="true"]{
        background:#0F766E !important;
        color:white !important;
    }

    /* Chat Cards */
    [data-testid="stChatMessage"]{
        background:white !important;
        border-radius:18px !important;
        border-left:5px solid #14B8A6 !important;
        box-shadow:0 8px 24px rgba(0,0,0,0.05) !important;
        padding:1rem !important;
    }

    /* Metrics */
    [data-testid="metric-container"]{
        background:white;
        border-radius:16px;
        padding:15px;
        box-shadow:0 6px 20px rgba(0,0,0,0.04);
    }

    /* Hide Streamlit */
    #MainMenu {visibility:hidden;}
    footer {visibility:hidden;}

    </style>
    """, unsafe_allow_html=True)

# --- 4. DYNAMIC AUTO-SLIDING CAROUSEL ---
facts_json = json.dumps(st.session_state.health_facts)

carousel_html = f"""
<style>
  .slider-container {{ width: 100%; height: 260px; overflow: hidden; border-radius: 16px; position: relative; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; box-shadow: 0 4px 15px rgba(0,0,0,0.08); margin-bottom: 20px;}}
  .slides {{ display: flex; transition: transform 0.6s cubic-bezier(0.25, 0.8, 0.25, 1); height: 100%; }}
  .slide {{ min-width: 100%; height: 100%; position: relative; }}
  .slide img {{ width: 100%; height: 100%; object-fit: cover; opacity: 0.85; background-color: #f0f0f0; }}
  .overlay {{ position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: linear-gradient(to top, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.1) 100%); }}
  .text-box {{ position: absolute; bottom: 15px; left: 15px; right: 15px; background: rgba(255,255,255,0.95); padding: 12px; border-radius: 10px; font-size: 13px; color: #111; box-shadow: 0 4px 10px rgba(0,0,0,0.15); line-height: 1.4;}}
  .badge {{ background: #D4F542; color: #111; padding: 2px 8px; border-radius: 12px; font-weight: bold; font-size: 11px; margin-bottom: 5px; display: inline-block;}}
</style>
<div class="slider-container"><div class="slides" id="slides"></div></div>
<script>
  const healthData = {facts_json};
  const slidesContainer = document.getElementById("slides");
  healthData.forEach(item => {{
    const slideDiv = document.createElement('div');
    slideDiv.className = 'slide';
    const encodedKeyword = encodeURIComponent(item.keyword + " aesthetic health");
    const imgUrl = `https://image.pollinations.ai/prompt/${{encodedKeyword}}?width=600&height=400&nologo=true`;
    slideDiv.innerHTML = `
      <img src="${{imgUrl}}" loading="lazy" onerror="this.src='https://picsum.photos/seed/${{Math.random()}}/600/400'">
      <div class="overlay"></div>
      <div class="text-box"><div class="badge">${{item.badge}}</div><br><b>Myth:</b> ${{item.myth}}<br><b>Fact:</b> ${{item.fact}}</div>
    `;
    slidesContainer.appendChild(slideDiv);
  }});
  const totalSlides = healthData.length;
  let currentIndex = 0;
  setInterval(() => {{
    currentIndex = (currentIndex + 1) % totalSlides;
    slidesContainer.style.transform = `translateX(-${{currentIndex * 100}}%)`;
  }}, 13000);
</script>
"""

# --- 5. LIVE SIDEBAR ---
with st.sidebar:
    st.markdown("## ⚙️ Dashboard")
    components.html(carousel_html, height=270)
    st.divider()
    st.subheader("💧 Water Tracker")
    st.info(
        "💡 Daily Tip: A 30-minute walk can reduce heart disease risk and improve mood."
    )
    st.progress(
        min(st.session_state.water_intake / 3000, 1.0)
    )
    st.caption(
        f"{st.session_state.water_intake} ml / 3000 ml"
    )

    st.divider()
    st.markdown("### 🚨 Emergency Contact")
    with st.container(border=True):
        emergency_name = st.text_input(
            "Contact Name",
            placeholder="e.g. Mom",
            key="emergency_name"
        )
        emergency_phone = st.text_input(
            "Phone Number",
            placeholder="+91 XXXXX XXXXX",
            key="emergency_phone"
        )
        if emergency_phone:
            st.success(f"📞 Emergency Contact Saved")

    st.divider()

    st.subheader("📋 Active Trackers")
    with st.expander("💊 Medications", expanded=True):
        if st.session_state.live_meds:
            for m in st.session_state.live_meds: st.markdown(f"✅ **{m['med']}** 🕒 {m['time']}")
        else: st.caption("No medicines added yet.")
    with st.expander("🏃‍♂️ Fitness Logs", expanded=True):
        if st.session_state.live_fitness:
            for f in st.session_state.live_fitness: st.markdown(f"🔥 **{f['activity']}** for {f['duration']} mins")
        else: st.caption("No fitness activity logged.")

# --- 6. MAIN SCREEN HEADER ---
col_empty, col_switch = st.columns([3, 1])
with col_switch:
    app_mode = st.selectbox("Select Space", ["🩺 Clinical Mode", "🌿 Soul Sanctuary"], label_visibility="collapsed")

st.write("") 

if app_mode == "🩺 Clinical Mode":
    st.markdown("<h1 style='font-size: 3.5rem; line-height: 1.1; padding-bottom: 10px;'>Your Personal<br><span style='color: #0F766E;'>Health Partner.</span></h1>", unsafe_allow_html=True)
    st.markdown("<p style='font-size: 1.2rem; margin-bottom: 30px;'>Advanced monitoring and AI diagnostics, wrapped in care.</p>", unsafe_allow_html=True)
    
    tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs(
        [
            "💬 Consultation",
            "📊 Analytics",
            "📄 Report Analyzer",
            "🛡️ Med-Safety",
            "🧘 Wellness",
            "🏥 Hospitals",
            "📅 Appointments"
        ]
    )

    # TAB 1: CONSULTATION 
    with tab1:
        st.caption("Try asking: 'Log Paracetamol at 10 AM' or 'I ran for 50 mins'")
        col_doc, col_info = st.columns([1, 4])

        with col_doc:
            st.image(
                "https://cdn-icons-png.flaticon.com/512/3774/3774299.png",
                width=140
            )

        with col_info:
            st.markdown("""
            ### 👩‍⚕️ Dr. HopeRise AI

            Your personal healthcare companion.

            ✅ Medicine Tracking  
            ✅ Fitness Monitoring  
            ✅ Health Insights  
            ✅ Report Analysis
            """)

        st.success("🟢 Dr. HopeRise is Online")
        st.write("---")
        if "med_messages" not in st.session_state:
            st.session_state.med_messages = [{"role": "assistant", "content": "Welcome! I am your AI Consultant. Tell me about your activities or ask me a health question!"}]
        
        for msg in st.session_state.med_messages:
            with st.chat_message(msg["role"]): st.markdown(msg["content"])
            
        if prompt := st.chat_input("Message your consultant..."):
            st.session_state.med_messages.append({"role": "user", "content": prompt})
            with st.chat_message("user"): st.markdown(prompt)
            
            with st.chat_message("assistant"):
                with st.spinner("Thinking..."):
                    # Get Raw Response from AI
                    raw_response = agent.chat_with_agent(prompt, persona_name="🩺 Medical")
                    
                    # --- 1. THE ADVANCED PARSER (Extracting Data before cleaning) ---
                    logged_something = False

                    # A. Fitness Parsing
                    fit_match = re.search(r'\[LOG_FITNESS:\s*(.*?),\s*(\d+)\]', raw_response)
                    fit_tool_match = re.search(r'<function=log_fitness_tool>(.*?)</function>', raw_response, re.DOTALL)
                    
                    if fit_match:
                        act_name = fit_match.group(1).strip()
                        duration = int(fit_match.group(2).strip())
                        db.add_fitness_log(act_name, str(duration))
                        st.session_state.live_fitness.append({"activity": act_name, "duration": duration})
                        st.toast(f"🔥 Logged & Saved: {act_name}")
                        logged_something = True
                    elif fit_tool_match:
                        try:
                            data = json.loads(fit_tool_match.group(1).strip())
                            act_name, duration = data.get("activity"), int(data.get("duration", 0))
                            db.add_fitness_log(act_name, str(duration))
                            st.session_state.live_fitness.append({"activity": act_name, "duration": duration})
                            st.toast(f"🔥 Logged & Saved: {act_name}")
                            logged_something = True
                        except: pass

                    # B. Medicine Parsing
                    med_match = re.search(r'\[LOG_MED:\s*(.*?),\s*(.*?)\]', raw_response)
                    med_tool_match = re.search(r'<function=add_medication_tool>(.*?)</function>', raw_response, re.DOTALL)
                    
                    if med_match:
                        med_name, med_time = med_match.group(1).strip(), med_match.group(2).strip()
                        db.add_medicine(med_name, med_time)
                        st.session_state.live_meds.append({"med": med_name, "time": med_time})
                        st.toast(f"💊 Logged & Saved: {med_name}")
                        logged_something = True
                    elif med_tool_match:
                        try:
                            data = json.loads(med_tool_match.group(1).strip())
                            med_name, med_time = data.get("name"), data.get("time")
                            db.add_medicine(med_name, med_time)
                            st.session_state.live_meds.append({"med": med_name, "time": med_time})
                            st.toast(f"💊 Logged & Saved: {med_name}")
                            logged_something = True
                        except: pass

                    # --- 2. THE CLEANER (Passing through the Shield) ---
                    clean_response = clean_ai_response(raw_response)
                    # Animated typing effect
                    import time

                    placeholder = st.empty()
                    typed_text = ""

                    for char in clean_response:
                        typed_text += char
                        placeholder.markdown(typed_text)
                        time.sleep(0.003)

    # TAB 2: LIVE ANALYTICS
    with tab2:
        st.markdown("### 📊 Live Health Analytics")
        st.caption("Add your daily logs here. Data is permanently saved to your database.")
        st.markdown("### 💧 Water Intake")

        water_amount = st.number_input(
            "Water Consumed (ml)",
            min_value=100,
            step=100,
            key="water_input"
        )
        if st.button("Add Water"):
            st.session_state.water_intake += water_amount
            st.success(f"Added {water_amount} ml")
            st.rerun()

        col_med_in, col_fit_in = st.columns(2)
        with col_med_in:
            with st.container(border=True):
                st.markdown("#### ➕ Add Medicine Log")
                new_med = st.text_input("Medicine Name", placeholder="e.g., Paracetamol", key="med_name")
                new_time = st.time_input("Time to take", key="med_time")
                if st.button("Save Medicine", type="primary", use_container_width=True):
                    if new_med:
                        time_str = new_time.strftime("%I:%M %p")
                        db.add_medicine(new_med, time_str) # SAVING TO DB
                        st.session_state.live_meds.append({"med": new_med, "time": time_str})
                        st.rerun()

        with col_fit_in:
            with st.container(border=True):
                st.markdown("#### ➕ Add Fitness Log")
                new_act = st.text_input("Activity", placeholder="e.g., Yoga, Running", key="fit_act")
                new_dur = st.number_input("Duration (in mins)", min_value=1, step=5, key="fit_dur")
                if st.button("Save Activity", type="primary", use_container_width=True):
                    if new_act:
                        db.add_fitness_log(new_act, str(new_dur)) # SAVING TO DB
                        st.session_state.live_fitness.append({"activity": new_act, "duration": new_dur})
                        st.rerun()
        score = 50
        score += min(
            len(st.session_state.live_fitness) * 5,
            25
        )
        score += min(
            st.session_state.water_intake // 200,
            15
        )
        score += min(
            len(st.session_state.live_meds) * 2,
            10
        )
        score = min(score, 100)
        st.markdown("## 🏆 Health Score")
        st.metric(
            "Overall Score",
            f"{score}/100"
        )
        st.markdown("### 🚦 Health Risk Indicator")

        if score >= 80:
            st.success("🟢 LOW RISK")
            st.info("Your lifestyle indicators look healthy.")
        elif score >= 60:
            st.warning("🟡 MODERATE RISK")
            st.info("Some habits can be improved for better health.")
        else:
            st.error("🔴 HIGH RISK")
            st.info("Consider improving hydration, activity and medication adherence.")

        risk_percent = 100 - score

        st.progress(risk_percent / 100)

        st.metric(
            "Risk Score",
            f"{risk_percent}%"
        )

        if score >= 80:
            st.success("Excellent health habits!")
        elif score >= 60:
            st.warning("Good progress. Keep going!")
        else:
            st.error("Your health score needs improvement.")
        st.write("---")

        # =========================
        # AI HEALTH INSIGHTS
        # =========================

        st.markdown("## 🧠 AI Health Insights")

        insights = []

        if st.session_state.water_intake < 1500:
            insights.append("💧 Your water intake is below recommended levels.")

        if len(st.session_state.live_fitness) < 3:
            insights.append("🏃 Try adding more physical activity this week.")

        if len(st.session_state.live_meds) > 5:
            insights.append("💊 You are managing multiple medications. Follow schedules carefully.")

        if not insights:
            st.success("🎉 Great job! Your health habits look balanced.")
        else:
            for item in insights:
                st.warning(item)

        # =========================
        # BMI CALCULATOR
        # =========================

        st.write("---")
        st.markdown("## ⚖️ BMI Calculator")

        col1, col2 = st.columns(2)

        with col1:
            weight = st.number_input(
                "Weight (kg)",
                min_value=1.0,
                value=60.0
            )

        with col2:
            height = st.number_input(
                "Height (m)",
                min_value=0.5,
                value=1.70
            )

        if height > 0:
            bmi = round(weight / (height * height), 2)

            st.metric("BMI", bmi)

            if bmi < 18.5:
                st.warning("Underweight")
            elif bmi < 25:
                st.success("Normal")
            elif bmi < 30:
                st.warning("Overweight")
            else:
                st.error("Obese")

        # =========================
        # ACHIEVEMENT BADGES
        # =========================

        st.write("---")
        st.markdown("## 🏅 Achievement Badges")

        badges = []

        if st.session_state.water_intake >= 3000:
            badges.append("💧 Hydration Hero")

        if len(st.session_state.live_fitness) >= 5:
            badges.append("🏃 Fitness Warrior")

        if len(st.session_state.live_meds) >= 3:
            badges.append("💊 Medication Master")

        if score >= 80:
            badges.append("🏆 Health Champion")

        if badges:
            for badge in badges:
                st.success(badge)
        else:
            st.info("Start logging activities to unlock badges.")


        st.write("---")
        col_header, col_download = st.columns([3, 1])
        with col_header: st.markdown("#### 📈 Your Live Trends")
            
        df_meds = pd.DataFrame(st.session_state.live_meds)
        df_fitness = pd.DataFrame(st.session_state.live_fitness)
        
        with col_download:
            if not df_fitness.empty:
                csv_data = df_fitness.to_csv(index=False).encode('utf-8')
                st.download_button("📥 Download My Data", data=csv_data, file_name="My_Health_Data.csv", mime="text/csv", use_container_width=True)

        col_t1, col_t2 = st.columns(2)
        with col_t1:
            st.markdown("**Medicine Schedule**")
            st.dataframe(df_meds, hide_index=True, use_container_width=True)
        with col_t2:
            st.markdown("**Fitness Logs**")
            st.dataframe(df_fitness, hide_index=True, use_container_width=True)
        st.write("")
        st.markdown("## 📅 Health Timeline")
        for med in st.session_state.live_meds:
            st.write(
                f"💊 {med['med']} at {med['time']}"
            )
        for fit in st.session_state.live_fitness:
            st.write(
                f"🏃 {fit['activity']} ({fit['duration']} mins)"
            )
        st.write("---")
        st.markdown("**Fitness Duration Graph (Live)**")
        if not df_fitness.empty:
            chart_data = df_fitness.groupby("activity")["duration"].sum().reset_index()
            palette = ["#3B82F6", "#10B981"] 
            chart_data["Bar_Color"] = [palette[i % 2] for i in range(len(chart_data))]
            st.bar_chart(chart_data, x="activity", y="duration", color="Bar_Color")
        else:
            st.info("Add some fitness logs to see your graph!")

    # TAB 3 & 4
    with tab3:
        st.markdown("### 📄 Smart Report Analyzer")
        st.caption("Upload your blood test or medical report. AI will explain it, translate it, and generate a PDF.")
        patient_name = st.text_input("👤 Patient Name (Used for PDF file name):", placeholder="e.g., Yash Patel")
        uploaded_file = st.file_uploader("Upload Report (Image)", type=["png", "jpg", "jpeg"])
        
        if uploaded_file is not None:
            with st.expander("👁️ View Uploaded Image Preview", expanded=False):
                st.image(uploaded_file, use_container_width=True, caption="Your Uploaded Report")
            if st.button("🧠 Analyze Report", type="primary"):
                with st.spinner("AI is reading and analyzing your report..."):
                    file_bytes = uploaded_file.getvalue()
                    result = agent.analyze_image_with_vision(file_bytes)
                    st.session_state.report_eng = result
                    st.session_state.report_hin = None
                    st.session_state.display_lang = "🇬🇧 English"
                    st.session_state.patient_name = patient_name

        if "report_eng" in st.session_state:
            st.write("---")
            col_lang, col_space = st.columns([2, 2])
            with col_lang:
                selected_lang = st.radio("Select Output Language:", ["🇬🇧 English", "🇮🇳 Easy Hinglish"], horizontal=True)
            if selected_lang == "🇮🇳 Easy Hinglish" and st.session_state.report_hin is None:
                with st.spinner("Translating to simple Hinglish..."):
                    st.session_state.report_hin = agent.translate_to_hinglish(st.session_state.report_eng)
            st.session_state.display_lang = selected_lang
            current_text = st.session_state.report_hin if st.session_state.display_lang == "🇮🇳 Easy Hinglish" else st.session_state.report_eng
            
            col_res, col_down = st.columns([3, 1])
            with col_res: st.markdown(f"#### 📑 AI Analysis Result ({selected_lang})")
            with col_down:
                pdf_bytes = create_professional_pdf(current_text)
                safe_name = st.session_state.patient_name.replace(" ", "_") if st.session_state.patient_name else "Patient"
                st.download_button(label="📄 Download PDF", data=pdf_bytes, file_name=f"{safe_name}_AI_Analysis.pdf", mime="application/pdf", use_container_width=True)
            st.info(current_text)

    with tab4:
        st.markdown("### 🛡️ Smart Medicine Safety Checker")
        st.caption("Avoid overdose and clashes. Let AI compare your old and new medicines.")
        if "med_stage" not in st.session_state: st.session_state.med_stage = "start"

        if st.session_state.med_stage == "start":
            issue = st.text_input("Kya takleef ho rahi hai aapko?", placeholder="e.g., Fever and headache")
            if st.button("Continue ➡️", type="primary"):
                if issue:
                    st.session_state.user_issue = issue
                    st.session_state.med_stage = "upload"
                    st.rerun()
                else: st.warning("Please describe your issue first.")

        elif st.session_state.med_stage == "upload":
            st.markdown(f"**Your Issue:** *{st.session_state.user_issue}*")
            c1, c2 = st.columns(2)
            with c1: 
                with st.container(border=True):
                    st.markdown("#### 🏠 Old Medicine")
                    old_mode = st.radio("How to input?", ["Type Name", "Upload Photo"], key="old_radio", horizontal=True)
                    if old_mode == "Type Name":
                        old_data = st.text_input("Enter Old Medicine", label_visibility="collapsed")
                        old_file = None
                    else:
                        old_file = st.file_uploader("Upload Old Photo", type=["png", "jpg", "jpeg"], key="old_up", label_visibility="collapsed")
                        old_data = None
            with c2: 
                with st.container(border=True):
                    st.markdown("#### 🩺 New Medicine")
                    new_mode = st.radio("How to input?", ["Type Name", "Upload Photo"], key="new_radio", horizontal=True)
                    if new_mode == "Type Name":
                        new_data = st.text_input("Enter New Medicine", label_visibility="collapsed")
                        new_file = None
                    else:
                        new_file = st.file_uploader("Upload New Photo", type=["png", "jpg", "jpeg"], key="new_up", label_visibility="collapsed")
                        new_data = None
            st.write("") 
            col_btn1, col_btn2 = st.columns([1, 4])
            with col_btn1:
                if st.button("⬅️ Back"):
                    st.session_state.med_stage = "start"
                    st.rerun()
            with col_btn2:
                if st.button("🧠 Analyze & Compare Safety", type="primary"):
                    if (old_data or old_file) and (new_data or new_file):
                        with st.spinner("AI is analyzing salts..."):
                            final_old = agent.analyze_image_with_vision(old_file.getvalue()) if old_file else old_data
                            final_new = agent.analyze_image_with_vision(new_file.getvalue()) if new_file else new_data
                            final_prompt = f"Issue: '{st.session_state.user_issue}'. Act as a highly expert Indian Healthcare AI. Compare active salts of Old Med: '{final_old}' and New Med: '{final_new}'. Are they safe together? Explain simply in Hinglish."
                            st.session_state.med_result = agent.chat_with_agent(final_prompt, persona_name="🩺 Medical")
                            st.session_state.med_stage = "result"
                            st.rerun()
                    else: st.error("Please provide both medicines.")

        elif st.session_state.med_stage == "result":
            st.markdown("### 🏁 AI Safety Verdict")
            st.success(st.session_state.med_result)
            if st.button("🔄 Check Another Medicine", type="primary"):
                st.session_state.med_stage = "start"
                st.rerun()
    with tab5:
        st.markdown("### 🤖 Daily Health Coach")

        goal = st.text_input(
            "Enter your health goal",
            placeholder="Lose 5kg in 2 months"
        )

        if st.button("Generate Plan"):
            with st.spinner("Creating your personalized plan..."):
                prompt = f"""
                Create a personalized health plan for:
                {goal}
                Include:
                - Diet recommendations
                - Exercise recommendations
                - Sleep schedule
                - Water intake
                - Daily habits
                Keep it practical and beginner friendly.
                """
                plan = agent.chat_with_agent(
                    prompt,
                    persona_name="🩺 Medical"
                )
                st.success(plan)
    with tab6:

        st.markdown("## 🏥 Nearby Hospitals")
        st.markdown("### ⭐ Recommended Hospitals")

        col1, col2 = st.columns(2)

        with col1:
            st.success("🏥 Medanta Hospital")
            st.caption("Multi-Speciality & Emergency Care")

            st.success("🏥 Artemis Hospital")
            st.caption("Advanced Surgical Care")

        with col2:
            st.success("🏥 Fortis Memorial")
            st.caption("Cardiology & Critical Care")

            st.success("🏥 Paras Hospital")
            st.caption("Trauma & Emergency Services")

        hospital_locations = [
            [28.4595, 77.0266, "Medanta Hospital"],
            [28.4350, 77.1130, "Fortis Memorial Research Institute"],
            [28.4744, 77.1000, "Artemis Hospital"],
            [28.4465, 77.1025, "Paras Hospital"]
        ]

        m = folium.Map(
            location=[28.4595, 77.0266],
            zoom_start=12
        )

        for lat, lon, name in hospital_locations:

            folium.Marker(
                [lat, lon],
                popup=name,
                tooltip=name,
                icon=folium.Icon(
                    color="red",
                    icon="plus",
                    prefix="fa"
                )
            ).add_to(m)

        st_folium(
            m,
            width=900,
            height=500
        )

        # GOOGLE MAPS NAVIGATION
        st.write("---")

        hospital = st.selectbox(
            "📍 Navigate To",
            [
                "Medanta Hospital Gurgaon",
                "Fortis Memorial Gurgaon",
                "Artemis Hospital Gurgaon",
                "Paras Hospital Gurgaon"
            ]
        )

        if st.button("Open in Google Maps"):
            hospital_query = hospital.replace(" ", "+")
            st.markdown(
                f"[🗺️ Open Navigation](https://www.google.com/maps/search/{hospital_query})"
            )


        st.write("---")

        st.markdown("### 🚨 Emergency Contacts")

        st.error("🚑 Ambulance: 108")
        st.warning("🚔 Police: 100")
        st.warning("🔥 Fire Brigade: 101")

        st.success("""
        ❤️ Emergency Tips

        • Stay calm

        • Share your exact location

        • Keep medical records ready

        • Inform family members

        • Follow emergency operator instructions
        """)
    
    with tab7:

        st.markdown("## 📅 Doctor Appointment Scheduler")
        st.info(
            "👨‍⚕️ Book appointments with specialists, track schedules, and receive reminders."
        )
        
        doctor = st.selectbox(
            "Select Doctor",
            [
                "Dr. Sharma - General Physician",
                "Dr. Gupta - Cardiologist",
                "Dr. Mehta - Dermatologist",
                "Dr. Verma - Orthopedic",
                "Dr. Kapoor - Pediatrician"
            ]
        )

        appointment_date = st.date_input(
            "Appointment Date"
        )

        appointment_time = st.time_input(
            "Appointment Time"
        )

        patient_name = st.text_input(
            "Patient Name"
        )

        reason = st.text_area(
            "Reason for Visit",
            placeholder="Describe your symptoms..."
        )

        if st.button("📅 Book Appointment"):

            if patient_name and reason:

                st.success(
                    f"""
                    ✅ Appointment Confirmed!

                    Doctor: {doctor}

                    Patient: {patient_name}

                    Date: {appointment_date}

                    Time: {appointment_time}

                    Reason: {reason}
                    """
                )
                st.balloons()

                st.info(
                    "📲 Reminder notification will be sent before appointment."
                )
            else:
                st.error("Please enter patient name and reason for visit.")

        st.write("---")

        st.markdown("### 👨‍⚕️ Available Doctors")

        col1, col2 = st.columns(2)

        with col1:
            st.success("👨‍⚕️ Dr. Sharma")
            st.caption("General Physician")
            st.caption("🟢 Available Today")

            st.success("❤️ Dr. Gupta")
            st.caption("Cardiologist")
            st.caption("🟢 Available Today")

        with col2:
            st.success("🦴 Dr. Verma")
            st.caption("Orthopedic")
            st.caption("🟡 Limited Slots")

            st.success("🧴 Dr. Mehta")
            st.caption("Dermatologist")
            st.caption("🟢 Available Today")

elif app_mode == "🌿 Soul Sanctuary":
    st.markdown("<h1 style='font-size: 3.5rem; line-height: 1.1; padding-bottom: 10px;'>Your Safe <span style='color: #0F766E;'>Space.</span></h1>", unsafe_allow_html=True)
    st.markdown("<p style='font-size: 1.2rem; margin-bottom: 30px;'>No judgment. Just a friend who listens.</p>", unsafe_allow_html=True)
    selected_counselor = st.radio("Who would you like to talk to?", ["👦 Arav", "👧 Ishani", "😎 Kabir", "👵 Meera"], horizontal=True)
    persona_key = selected_counselor.split(" ")[1] 
    st.write("---")

    if "soul_stage" not in st.session_state: st.session_state.soul_stage = "start"

    if st.session_state.soul_stage == "start":
        st.markdown(f"### {persona_key} is here. Kaisa feel kar rahe ho aaj?")
        col1, col2 = st.columns(2)
        with col1:
            if st.button("📚 Academic Stress", use_container_width=True): st.session_state.initial_mood = "Padhai ka stress"
            if st.button("😶 Feeling Lonely", use_container_width=True): st.session_state.initial_mood = "Feeling lonely"
        with col2:
            if st.button("😴 Sleep Issues", use_container_width=True): st.session_state.initial_mood = "Sleep issues"
            if st.button("❤️ Heartbreak", use_container_width=True): st.session_state.initial_mood = "Relationship issues"
        st.write("")
        custom_mood = st.text_input("Or write your heart out...", placeholder="Today I am feeling...")
        if st.button("Open Up", type="primary"):
            if custom_mood: st.session_state.initial_mood = custom_mood
            if "initial_mood" in st.session_state:
                st.session_state.soul_stage = "chat"
                st.session_state.soul_messages = []
                st.rerun()

    elif st.session_state.soul_stage == "chat":
        if st.button("🔄 End Session"):
            st.session_state.soul_stage = "start"
            st.session_state.soul_messages = []
            st.rerun()
            
        if not st.session_state.soul_messages:
            init_prompt = f"The user is feeling: {st.session_state.initial_mood}. Start the conversation smoothly as {persona_key}."
            # Shield applied here too
            raw_init = agent.chat_with_agent(init_prompt, persona_name=selected_counselor)
            clean_init = clean_ai_response(raw_init)
            st.session_state.soul_messages.append({"role": "assistant", "content": clean_init})

        for msg in st.session_state.soul_messages:
            with st.chat_message(msg["role"]): st.markdown(msg["content"])

        if prompt := st.chat_input(f"Talk to {persona_key}..."):
            st.session_state.soul_messages.append({"role": "user", "content": prompt})
            with st.chat_message("user"): st.markdown(prompt)
            with st.chat_message("assistant"):
                with st.spinner(f"{persona_key} is typing..."):
                    # Shield applied for continuous chat
                    raw_response = agent.chat_with_agent(prompt, persona_name=selected_counselor)
                    
                    clean_response = clean_ai_response(raw_response)

                    # Animated typing effect
                    import time

                    placeholder = st.empty()
                    typed_text = ""

                    for char in clean_response:
                        typed_text += char
                        placeholder.markdown(typed_text)
                        time.sleep(0.003)

                    st.markdown(clean_response)

                    audio = agent.generate_voice(clean_response)
                    st.audio(audio, format="audio/mp3")

                    st.session_state.soul_messages.append(
                        {"role": "assistant", "content": clean_response}
                    )
                    # clean_response = clean_ai_response(raw_response)
                    
                    # st.markdown(clean_response)
                    # st.session_state.soul_messages.append({"role": "assistant", "content": clean_response})


